# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            smapy.docs
tagline:          'social media anatomist'
description:      'Socail media anatomist for Python / Documentation'
url:              http://sobach.github.io/smapy/

author:
  name:           'Alexander Tolmach'
  url:            http://www.facebook.com/atolmach

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           http://github.com/Sobach/smapy/