# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:       ["tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            smapy
tagline:          'social media anatomist'
description:      'Socail media anatomist for Python <br/> Documentation'
url:              http://sobach.github.io/smapy/

author:
  name:           'Alexander Tolmach'
  url:            http://www.facebook.com/atolmach

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           http://github.com/Sobach/smapy/